// <copyright file="PreOperationcontactUpdate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>2/14/2018 1:36:41 PM</date>
// <summary>Implements the PreOperationcontactUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using CrmCalculations;
using CrmEarlyBound;
using Microsoft.Xrm.Sdk;

namespace FinalDynamicsChallenge.contactsPlugin
{
  public class PreOperationcontactUpdate : PluginBase
  {

    public PreOperationcontactUpdate(string unsecure, string secure)
        : base(typeof(PreOperationcontactUpdate))
    {

      // TODO: Implement your custom configuration handling.
    }
    protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
    {
      if (localContext == null)
      {
        throw new InvalidPluginExecutionException("localContext");
      }

      IPluginExecutionContext context = localContext.PluginExecutionContext;

      if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)
      {
        Entity entity = (Entity)context.PreEntityImages["Target"];
        Contact contact = entity.ToEntity<Contact>();
        Entity preEntity = (Entity)context.PreEntityImages["contactPreImage"];
        Contact preContact = preEntity.ToEntity<Contact>();

        try
        {
          Calculations calc = new Calculations();
          contact.di_age = calc.CalculateAge(contact, preContact);
          contact.di_EsitimatedReturnFinal = calc.CalculateEstReturn(contact, preContact);
          contact.di_maturity_date = calc.CalculateMaturityDate(contact, preContact);
        }
        catch (Exception ex)
        {
          throw new InvalidPluginExecutionException("An error occured in the plugin:", ex);
        }
      }
    }
  }
}

